language: node_js

node_js:
  - 6.10.1
  - 6.10.2

services:
  - postgresql

before_script:
  - psql -c 'create database travis' -U postgres
  - npm install -S mysql
  - npm run db:migrate:undo
  - npm run db:migrate
  - npm run db:seed

script: 
  - npm run test:travis

after_success:
  - npm run coverage

notifications:
  email:
    recipients:
      - folusho.oladipo@andela.com
    on_success: never
    on_failure: always
