language: node_js

node_js:
  - 6.10.1
  - 6.10.2

before_script:
  - npm install

script: 
  - npm test

after_success:
  - npm run coverage

notifications:
  email:
    recipients:
      - folusho.oladipo@andela.com
    on_success: never
    on_failure: always
